version: "3"
services:
  api-database:
    image: mongo:5.0
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: campsite-image
    ports:
      - 8080:8080
    links:
      - api-database